// <auto-generated />
using BusTickets.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BusTickets.DataAccess.Migrations
{
    [DbContext(typeof(BusTicketDbContext))]
    [Migration("20170914145711_Create some Tables")]
    partial class CreatesomeTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusTickets.DataAccess.BusStation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CityID");

                    b.HasKey("ID");

                    b.ToTable("BusStations");
                });

            modelBuilder.Entity("BusTickets.DataAccess.BusStop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CityID");

                    b.Property<int>("JourneyID");

                    b.HasKey("ID");

                    b.ToTable("BusStops");
                });

            modelBuilder.Entity("BusTickets.DataAccess.CitiesNearby", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CityID");

                    b.HasKey("ID");

                    b.ToTable("CitiesNearbys");
                });

            modelBuilder.Entity("BusTickets.DataAccess.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BusTickets.DataAccess.Journey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArrivalStationID");

                    b.Property<int>("DepartureStationID");

                    b.HasKey("ID");

                    b.ToTable("Journeys");
                });
#pragma warning restore 612, 618
        }
    }
}
